### ISSUE TITLE
[Feature Request] Putting the theme in Melpa for ease of installation.

### ISSUE THREAD

**Issue by fleurc** [Minimal-Mistakes/emacs#1]
Hi,
I use this theme as my default theme in emacs, and it is simply astounding on how good it feels.
I love the work put into it and would appreciate it even more if it would get added to Melpa.
Melpa is one of the online packaging repos for themes, extensions and basically everything that Emacs can use.
It makes it easy to install and in cases of Spacemacs and similar forks (distros) of emacs it would get rid of the annoying issue of it constantly verifying for the package in Melpa, where it doesn't exist.

I would be happy to help in any way towards this, but i also don't know how to package something on Melpa, i'm just a normal user of it.

**Comment by fleurc** [comment]
If useful, here is their Getting Started guide, which contains a simple explanation of how to put a package there.

[](https://melpa.org/#/getting-started)

**Comment by The-Repo-Club** [comment]
I will take a look into this when I get home from work in the next few days and get it uploaded onto there thanks for the support of using my theme

**Comment by The-Repo-Club** [comment]
https://github.com/melpa/melpa/blob/master/recipes/dracula-theme ok so this should be pretty easy I'd just make one like this for our own theme and boom it be done :) I'll work on a PR for it later tonight after I'm done work

**Comment by The-Repo-Club** [comment]
@fleurc https://github.com/melpa/melpa/pull/8065 the pull request has been made i will add it to the readme after it has been accepted

**Comment by fleurc** [comment]
Thanks for the good work! I will take a look at your build after work. I'm already really happy with the help, again, thank you!

**Comment by The-Repo-Club** [comment]
i am hoping to submit it to [minimal-mistakes-theme](https://elpa.nongnu.org/nongnu/minimal-mistakes-theme.html) (link wont work until its been accepted though)

**Comment by fleurc** [comment]
That's the shortcuts of your emacs? Also you prolly have me on Telegram, i was Code from the Endeavour group

**Comment by The-Repo-Club** [comment]
yes them screenshots are  my keybinds :)

**Comment by fleurc** [comment]
Oh, nice, i use Spacemacs, but i don't use all its keybinds, i use only M-x, M-Enter-i, and Vim keys most often.

**Comment by The-Repo-Club** [comment]
ya I was going to use spacemacs but then I thought hell let's just build my own then I know everything that's gone into it and no weastage and bloat
